#!/usr/bin/env python3
"""Test BAI2 generation with normal balances (no suspicious data)"""

import sys
sys.path.append('.')
from function_app import reconcile_transactions, convert_to_bai2

def test_normal_bai2():
    """Test BAI2 generation with normal, non-suspicious balances"""
    
    print("🧪 TESTING NORMAL OPENING/CLOSING BALANCE IN BAI2 GENERATION")
    print("=" * 70)
    print("📊 Simulating a normal statement:")
    print("   Opening Balance: $5,000.00")
    print("   Total Deposits:  $2,500.00") 
    print("   Total Withdrawals: $1,200.00")
    print("   Closing Balance: $6,300.00")
    print("   ✅ Expected Close: $6,300.00 (BALANCED)")
    print()
    
    # Create test data with normal balances
    test_data = {
        "opening_balance": {"amount": 5000.00},
        "closing_balance": {"amount": 6300.00},
        "transactions": [
            {"date": "2025-08-04", "amount": 1500.00, "description": "Deposit 1", "type": "deposit"},
            {"date": "2025-08-04", "amount": 1000.00, "description": "Deposit 2", "type": "deposit"},
            {"date": "2025-08-04", "amount": -600.00, "description": "Withdrawal 1", "type": "withdrawal"},
            {"date": "2025-08-04", "amount": -600.00, "description": "Withdrawal 2", "type": "withdrawal"}
        ],
        "account_number": "1234567",
        "routing_number": "113122655"
    }
    
    print("🔄 Running reconciliation...")
    reconciliation_summary = reconcile_transactions(test_data)
    print(f"✅ Reconciliation completed successfully")
    
    print("🔄 Converting to BAI2 format...")
    bai2_content = convert_to_bai2(test_data, "normal_statement.pdf", reconciliation_summary, "113122655")
    
    # Extract just the comments section
    lines = bai2_content.split('\n')
    comments_start = -1
    comments_end = -1
    
    for i, line in enumerate(lines):
        if line.startswith('#Generated by BankStatementAgent'):
            comments_start = i
        elif comments_start >= 0 and not line.startswith('#') and line.strip():
            comments_end = i
            break
    
    if comments_end == -1:
        comments_end = len(lines)
    
    comments_section = '\n'.join(lines[comments_start:comments_end])
    
    print("✅ BAI2 COMMENTS WITH NORMAL BALANCES:")
    print("=" * 80)
    print(comments_section)
    print("=" * 80)
    
    print()
    print("🎯 EXPECTED BEHAVIOR:")
    print("   ✅ Should show both opening and closing balances")
    print("   ✅ Should show full reconciliation calculation")
    print("   ✅ Should show balance difference (should be $0.00)")
    print("   ✅ Should show 'BALANCED' status")

if __name__ == "__main__":
    test_normal_bai2()
