#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Test bank name extraction with 500 real bank names
"""

def extract_complete_bank_name_from_line(line):
    """Extract complete bank name from a single line"""
    # Common bank name endings that indicate where to stop
    bank_endings = ['bank', 'union', 'financial', 'trust', 'services', 'corp', 'corporation', 'company', 'co']
    # Common connecting words in bank names
    connecting_words = ['of', 'and', '&', 'the', 'for']
    
    words = line.split()
    if not words:
        return None
    
    # Special case: If line starts with "Bank of [Something]", take the full name
    if words[0].lower() == 'bank' and len(words) >= 3 and words[1].lower() in connecting_words:
        # Look for the next 2-3 words as the complete name
        if len(words) >= 3:
            bank_name = ' '.join(words[:3])  # "Bank of America"
            return bank_name.strip()
    
    # Look for natural stopping points
    for i, word in enumerate(words):
        word_lower = word.lower().rstrip('.,')
        
        # Stop at obvious non-bank words FIRST (before checking bank endings)
        if word_lower in ['report', 'statement', 'date', 'page', 'account', 'balance', 'type', 'bai', 'test']:
            if i > 0:  # If we have some words before this
                bank_name = ' '.join(words[:i])
                return bank_name.strip()
            break
        
        # If we hit a bank ending, include it and stop
        if word_lower in bank_endings:
            bank_name = ' '.join(words[:i+1])
            return bank_name.strip()
    
    # If no clear ending found, take the whole line if it's reasonable length
    if len(words) <= 6 and len(line) <= 50:
        return line.strip()
    
    return None

# 500 real bank names from across the United States
REAL_BANK_NAMES = [
    # Major National Banks
    "Bank of America",
    "JPMorgan Chase Bank",
    "Wells Fargo Bank",
    "Citibank",
    "U.S. Bank",
    "PNC Bank",
    "Truist Bank",
    "TD Bank",
    "Capital One Bank",
    "Fifth Third Bank",
    
    # Regional Banks
    "Regions Bank",
    "KeyBank",
    "Citizens Bank",
    "M&T Bank",
    "Huntington National Bank",
    "Comerica Bank",
    "Zions Bancorporation",
    "First Citizens Bank",
    "Synovus Bank",
    "Valley National Bank",
    
    # Community Banks
    "First National Bank",
    "Community Bank",
    "Farmers Bank",
    "Merchants Bank",
    "Heritage Bank",
    "Security Bank",
    "Liberty Bank",
    "Independent Bank",
    "Pinnacle Bank",
    "Premier Bank",
    
    # Credit Unions
    "Navy Federal Credit Union",
    "State Employees Credit Union",
    "Pentagon Federal Credit Union",
    "Boeing Employees Credit Union",
    "Golden 1 Credit Union",
    "Alliant Credit Union",
    "BECU",
    "USAA Federal Savings Bank",
    "SchoolsFirst Federal Credit Union",
    "America First Credit Union",
    
    # State-Specific Banks
    "Bank of the West",
    "Eastern Bank",
    "Western Bank",
    "Northern Trust",
    "Southern Bank",
    "Central Bank",
    "Atlantic Union Bank",
    "Pacific Premier Bank",
    "Mountain West Bank",
    "Great Western Bank",
    
    # Multi-word Banks
    "First National Bank of America",
    "Bank of New York Mellon",
    "First Republic Bank",
    "Silicon Valley Bank",
    "Signature Bank",
    "Webster Bank",
    "People's United Bank",
    "Associated Bank",
    "Old National Bank",
    "United Community Bank",
    
    # Trust and Investment Banks
    "Northern Trust Company",
    "State Street Bank and Trust",
    "BNY Mellon Trust Company",
    "Goldman Sachs Bank USA",
    "Morgan Stanley Bank",
    "Charles Schwab Bank",
    "Fidelity Management Trust Company",
    "Vanguard Fiduciary Trust Company",
    "Bank of New York Mellon Trust Company",
    "Deutsche Bank Trust Company",
    
    # Savings Banks
    "Dollar Bank Federal Savings Bank",
    "Emigrant Bank",
    "Marcus by Goldman Sachs Bank",
    "American Express National Bank",
    "Discover Bank",
    "Ally Bank",
    "Capital One 360",
    "CIT Bank",
    "Synchrony Bank",
    "Barclays Bank Delaware",
    
    # Agricultural Banks
    "Farm Credit Bank",
    "AgriBank",
    "CoBank",
    "AgFirst Farm Credit Bank",
    "Texas Farm Credit Bank",
    "Northwest Farm Credit Services",
    "Farm Credit Services of America",
    "AgCredit",
    "Rural 1st",
    "Farmer Mac",
    
    # Industrial Banks
    "BMW Bank of North America",
    "Toyota Motor Credit Corporation",
    "Ford Motor Credit Company",
    "General Motors Financial",
    "Harley-Davidson Financial Services",
    "John Deere Financial",
    "Caterpillar Financial Services",
    "GE Capital Bank",
    "Mercedes-Benz Financial Services",
    "Volvo Financial Services",
    
    # Additional Major Banks
    "VERABANK",
    "RCB Bank",
    "Stock Yards Bank and Trust",
    "First Citizens Bank and Trust",
    "Frost Bank",
    "Comerica Bank",
    "Zions First National Bank",
    "First Interstate Bank",
    "Banner Bank",
    "Columbia Bank",
    
    # More Regional Banks
    "Umpqua Bank",
    "Sterling Bank",
    "Texas Capital Bank",
    "Prosperity Bank",
    "Woodforest National Bank",
    "Green Dot Bank",
    "MetaBank",
    "Republic Bank",
    "Iberiabank",
    "Hancock Whitney Bank",
    
    # More Community Banks
    "First Financial Bank",
    "Heartland Bank",
    "Midwest Bank",
    "Cornerstone Bank",
    "Gateway Bank",
    "Benchmark Bank",
    "Crossroads Bank",
    "MainStreet Bank",
    "Village Bank",
    "Hometown Bank",
    
    # Banks with Location Names
    "Bank of Hawaii",
    "First Bank of Delaware",
    "Virginia Commerce Bank",
    "Texas State Bank",
    "California Bank and Trust",
    "Arizona Bank and Trust",
    "Colorado State Bank",
    "Nevada State Bank",
    "Utah Community Bank",
    "Wyoming Bank and Trust",
    
    # Banks with Company Suffixes
    "First United Bank and Trust Company",
    "National Bank and Trust Company",
    "Security National Bank and Trust",
    "Citizens National Bank and Trust",
    "First State Bank and Trust Company",
    "Community National Bank and Trust",
    "Farmers and Merchants Bank",
    "First Merchants Bank",
    "Merchants and Farmers Bank",
    "Bank and Trust Company",
    
    # Credit Union Variations
    "Municipal Credit Union",
    "Teachers Credit Union",
    "Police and Fire Credit Union",
    "Healthcare Federal Credit Union",
    "Technology Credit Union",
    "University Credit Union",
    "Community Credit Union",
    "Educational Systems Credit Union",
    "Public Service Credit Union",
    "Federal Employees Credit Union",
    
    # Foreign Bank Branches in US
    "Bank of Montreal",
    "Royal Bank of Canada",
    "Toronto-Dominion Bank",
    "Bank of Nova Scotia",
    "HSBC Bank USA",
    "Barclays Bank Delaware",
    "Deutsche Bank USA",
    "UBS Bank USA",
    "Credit Suisse USA",
    "Banco Santander",
    
    # Specialty Banks
    "Cross River Bank",
    "Square 1 Bank",
    "First Technology Bank",
    "Bridge Bank",
    "Live Oak Bank",
    "Axos Bank",
    "Radius Bank",
    "TIAA Bank",
    "BBVA USA",
    "MUFG Union Bank",
    
    # Additional Banks (150-200)
    "AmeriServ Financial Bank",
    "Anchor Bank",
    "Apple Bank for Savings",
    "Arvest Bank",
    "Atlantic Capital Bank",
    "Banc of California",
    "BancFirst",
    "BancorpSouth Bank",
    "Bank Forward",
    "Bank Independent",
    "Bank of Guam",
    "Bank of Marin",
    "Bank of New Hampshire",
    "Bank of Oak Ridge",
    "Bank of Oklahoma",
    "Bank of Springfield",
    "Bank of the Ozarks",
    "Bank Rhode Island",
    "BankNewport",
    "BankUnited",
    "Bar Harbor Bank and Trust",
    "BCB Community Bank",
    "Beneficial Bank",
    "Berkshire Bank",
    "Blue Hills Bank",
    "Bremer Bank",
    "Brookline Bank",
    "Buffalo Savings Bank",
    "ByLine Bank",
    "Cambridge Savings Bank",
    "Cape Ann Savings Bank",
    "Cape Cod Five Cents Savings Bank",
    "Capital Bank",
    "Capital City Bank",
    "Carver State Bank",
    "Cathay Bank",
    "Century Bank",
    "Chemical Bank",
    "Choice Financial Group",
    "City National Bank",
    "Coastal Federal Credit Union",
    "Colonial Savings Bank",
    "Commerce Bank",
    "Community Bank of the Chesapeake",
    "Community First Bank",
    "ConnectOne Bank",
    "Cornerstone Community Bank",
    "Country Bank",
    "Cross County Savings Bank",
    "Danvers Savings Bank",
    "Dedham Institution for Savings",
    "Dime Community Bank",
    "East Boston Savings Bank",
    "Enterprise Bank and Trust",
    "Equity Bank",
    "Esquire Bank",
    "Evans Bank",
    "Evergreen Bank Group",
    "Exchange Bank",
    "F&M Bank",
    "Family Bank",
    "Farmers and Merchants Bank of Central California",
    "Farmers Bank and Trust",
    "Federal Savings Bank",
    "Fidelity Bank",
    "First American Bank",
    "First Bancorp",
    "First Bank",
    "First Bank and Trust",
    "First Commonwealth Bank",
    "First Community Bank",
    "First Federal Bank",
    "First Federal Savings Bank",
    "First Hawaii Bank",
    "First Horizon Bank",
    "First Ipswich Bank",
    "First National Bank Alaska",
    "First National Bank of Pennsylvania",
    "First National Bank of Tennessee",
    "First National Community Bank",
    "First Security Bank",
    "First Southern Bank",
    "First State Bank",
    "FirstBank",
    "Flagstar Bank",
    "Florida Capital Bank",
    "Fulton Bank",
    "Glacier Bank",
    "Great Southern Bank",
    "Guaranty Bank",
    "Harford Bank",
    "Hawthorn Bank",
    "HNB First Bank",
    "Home Bank",
    "Hope Bank",
    "Horizon Bank",
    "Independence Bank",
    "Inland Bank and Trust",
    "International Bank of Commerce",
    "Iowa State Bank",
    "Jonestown Bank and Trust",
    "KS StateBank",
    "Lake City Bank",
    "Lakeland Bank",
    "LegacyTexas Bank",
    "Level One Bank",
    "Macatawa Bank",
    "Malvern Bank",
    "Marine Bank",
    "Marquette Bank",
    "MidFirst Bank",
    "Midland States Bank",
    "MidSouth Bank",
    "MidWestOne Bank",
    "Millennium Bank",
    "Mission Bank",
    "MutualBank",
    "National Bank of Arizona",
    "National Bank of Commerce",
    "National Exchange Bank and Trust",
    "NBT Bank",
    "New Peoples Bank",
    "NewBridge Bank",
    "Norwood Bank",
    "Ocean Bank",
    "Origin Bank",
    "Ozark Bank",
    "Park Sterling Bank",
    "Pathfinder Bank",
    "Peapack-Gladstone Bank",
    "Peoples Bank",
    "Peoples Bank of Alabama",
    "PeoplesBank",
    "Pilot Bank",
    "Pioneer Bank",
    "Pinnacle Financial Partners",
    "PlainsCapital Bank",
    "Preferred Bank",
    "Prime Bank",
    "Princeton Bank",
    "Provident Bank",
    "Pulaski Bank",
    "Quantum National Bank",
    "Quontic Bank",
    "Red River Bank",
    "Reliant Bank",
    "Renasant Bank",
    "Resource Bank",
    "RiverHills Bank",
    "Rockland Trust",
    "Safra National Bank",
    "Sandy Spring Bank",
    "Seacoast Bank",
    "Security Bank and Trust",
    "Security State Bank",
    "Simmons Bank",
    "South State Bank",
    "Southside Bank",
    "Southwest Bank",
    "Spirit of Texas Bank",
    "State Bank and Trust",
    "State Bank of India",
    "StellarOne Bank",
    "Sun National Bank",
    "SunTrust Bank",
    "Sunrise Bank",
    "Table Rock Community Bank",
    "Tompkins Trust Company",
    "TriCo Bancshares",
    "TriState Capital Bank",
    "Troy Bank and Trust",
    "United Bank",
    "United Missouri Bank",
    "Unity Bank",
    "University Bank",
    "USAA",
    "Valley Bank",
    "Veridian Credit Union",
    "Victory Bank",
    "Wainscott Bank",
    "Washington Federal",
    "WashingtonFirst Bank",
    "WesBanco Bank",
    "West Bank",
    "West Texas National Bank",
    "Western Alliance Bank",
    "Western State Bank",
    "Westfield Bank",
    "Wintrust Bank",
    "Wise Bank",
    "York Traditions Bank",
    "Zions Bank",
    
    # Banks with Challenging Names (300-350)
    "1st Bank",
    "1st Source Bank",
    "21st Century Bank",
    "360 Federal Credit Union",
    "4Front Credit Union",
    "5Star Bank",
    "A+ Federal Credit Union",
    "AAA Bank",
    "ABCO Federal Credit Union",
    "ABC Bank",
    "Academy Bank",
    "Access Bank",
    "Acclaim Federal Credit Union",
    "ACE Credit Union",
    "Action Bank",
    "Advantage Bank",
    "Affinity Bank",
    "Affinity Federal Credit Union",
    "AimBank",
    "Air Force Federal Credit Union",
    "AltaOne Federal Credit Union",
    "America's Credit Union",
    "American Bank",
    "American Eagle Bank",
    "American Heritage Bank",
    "American Trust and Savings Bank",
    "Americorp Bank",
    "Amoco Federal Credit Union",
    "Anchor Bank",
    "Apple Federal Credit Union",
    "Architectural Financial Credit Union",
    "Armed Forces Bank",
    "Arrow Bank",
    "Astoria Bank",
    "Atlantic Community Bank",
    "Atlas Bank",
    "Austin Bank",
    "Avenue Bank",
    "Axiom Bank",
    "Baden State Bank",
    "Baltic State Bank",
    "Bank 7",
    "Bank 34",
    "Bank of Akron",
    "Bank of Alapaha",
    "Bank of Botetourt",
    "Bank of Brookfield",
    "Bank of Cadiz and Trust Company",
    "Bank of Clarendon",
    "Bank of Coushatta",
    "Bank of Dickson",
    "Bank of Fayette County",
    "Bank of George",
    "Bank of Kirksville",
    "Bank of Labor",
    "Bank of Lincoln County",
    "Bank of Luxemburg",
    "Bank of Madison",
    "Bank of Mitchell",
    "Bank of Montgomery",
    "Bank of Morton",
    "Bank of Newman Grove",
    "Bank of Odessa",
    "Bank of Palmer",
    "Bank of Pontiac",
    "Bank of Prairie Village",
    "Bank of Ripley",
    "Bank of Romney",
    "Bank of Ruston",
    "Bank of Salem",
    "Bank of Southside Virginia",
    "Bank of Star City",
    "Bank of Stockton",
    "Bank of Sullivan",
    "Bank of Summers",
    "Bank of Tampa",
    "Bank of Tescott",
    "Bank of Utica",
    "Bank of Vernon",
    "Bank ofVersailles",
    "Bank of Walterboro",
    "Bank of Washington",
    "Bank of Wiggins",
    "Bank of Winnfield and Trust Company",
    "Bank of York",
    "Bank of Zachary",
    "BankCherokee",
    "BankFirst Financial Services",
    "BankLiberty",
    "BankPlus",
    "BankSouth",
    "BankStar Financial",
    "BankTennessee",
    "BankTrust",
    "Banner County Bank",
    "Barrington Bank and Trust",
    "Bay Bank",
    "Bay State Savings Bank",
    "Bayport Credit Union",
    "Beach First National Bank",
    "Beacon Federal",
    "Bear State Bank",
    "Bedford Federal Bank",
    "Bell Bank",
    "Belmont Savings Bank",
    "BenchMark Bank",
    "Berkshire Hills Bancorp",
    "Best Bank",
    "Bison State Bank",
    "Black Hills Federal Credit Union",
    "Blackhawk Bank and Trust",
    "Blue Grass Savings Bank",
    "BluePeak Credit Union",
    "Bluestem National Bank",
    "BOK Financial",
    "Border State Bank",
    "Boston Private Bank and Trust Company",
    "Boulevard Bank",
    "Bradford National Bank",
    "Branch Banking and Trust Company",
    "BrandywineBANK",
    "Brickyard Bank",
    "Bridgewater Bank",
    "Brighton Bank",
    "Bristol County Savings Bank",
    "Brookhaven Bank",
    "Brotherhood Bank and Trust",
    "Brown County State Bank",
    "Bruning State Bank",
    "Bryant Bank",
    "BSB Bank",
    "Buckeye State Bank",
    "Buffalo Prairie State Bank",
    "Burke and Herbert Bank",
    "Business Bank of Texas",
    "Butler Bank",
    "C&F Bank",
    "Cache Valley Bank",
    "California Pacific Bank",
    "Cambridge Trust Company",
    "Camden National Bank",
    "Canandaigua National Bank and Trust",
    "Capstone Bank",
    "Cardinal Bank",
    "Carolina Bank and Trust",
    "Carolina Premier Bank",
    "Carrollton Bank",
    "Carter Bank and Trust",
    "Casey State Bank",
    "Castle Bank",
    "Catskill Hudson Bank",
    "CBTC Bank",
    "Cedar Rapids Bank and Trust",
    "Cedar Security Bank",
    "CedarStone Bank",
    "Celtic Bank",
    "CenterState Bank",
    "Central Bank of Boone County",
    "Central Bank of Kansas City",
    "Central Bank of Lake of the Ozarks",
    "Central Bank of St. Louis",
    "Central Federal Savings and Loan",
    "Central National Bank",
    "Central Pacific Bank",
    "Central State Bank",
    "Central Valley Community Bank",
    "Century Bank of the Ozarks",
    "Century Savings Bank",
    "Champlain National Bank",
    "Charter Bank",
    "Charter Oak Federal Credit Union",
    "Chatelain Bank",
    "Chemung Canal Trust Company",
    "Cherokee Bank",
    "Cherokee State Bank",
    "Chesapeake Bank",
    "Choice Bank",
    "ChoiceOne Bank",
    "Citibank Delaware",
    "Citizens Alliance Bank",
    "Citizens and Northern Bank",
    "Citizens Bank and Trust",
    "Citizens Bank of Cumberland County",
    "Citizens Bank of Edmond",
    "Citizens Bank of Mukwonago",
    "Citizens Community Bank",
    "Citizens Deposit Bank and Trust",
    "Citizens First Bank",
    "Citizens Independent Bank",
    "Citizens National Bank of Albion",
    "Citizens National Bank of Cheboygan",
    "Citizens National Bank of Meridian",
    "Citizens National Bank of Paris",
    "Citizens National Bank of Quitman",
    "Citizens Savings Bank",
    "Citizens State Bank",
    "Citizens State Bank of Midwest City",
    "Citizens State Bank of Tyler",
    "Citizens Trust Bank",
    "Citizens Union Bank",
    "City Bank",
    "City Bank and Trust",
    "City First Bank",
    "City National Bank and Trust",
    "City National Bank of Florida",
    "City National Bank of New Jersey",
    "City National Bank of West Virginia",
    "City State Bank",
    "Citywide Banks",
    "Clackamas County Bank",
    "Clare Bank",
    "Clarence State Bank",
    "Classic Bank",
    "Clear Mountain Bank",
    "ClearView Federal Credit Union",
    "Coastal Community Bank",
    "Coastal States Bank",
    "CoBiz Bank",
    "Coconut Grove Bank",
    "Cole Taylor Bank",
    "Colonial Bank",
    "Colorado East Bank and Trust",
    "Colorado Federal Savings Bank",
    "Columbia River Bank",
    "Commercial Bank",
    "Commercial Bank and Trust",
    "Commercial Bank of Texas",
    "Commercial National Bank",
    "Commercial Savings Bank",
    "Commonwealth Bank and Trust",
    "Community Bank and Trust",
    "Community Bank of Broward",
    "Community Bank of Mississippi",
    "Community Bank of Oak Park River Forest",
    "Community Bank of Pleasant Hill",
    "Community Bank of the Bay",
    "Community Banks of Colorado",
    "Community Capital Bank",
    "Community Development Bank",
    "Community Federal Savings Bank",
    "Community Financial Services Bank",
    "Community First Bank and Trust",
    "Community National Bank and Trust",
    "Community Resource Bank",
    "Community Spirit Bank",
    "Community State Bank",
    "Community Trust and Banking Company",
    "Community West Bank",
    "Compeer Financial",
    "Concordia Bank and Trust",
    "Congressional Bank",
    "Connecticut Community Bank",
    "Cornerstone Bank",
    "Cornerstone Community Bank",
    "Country Club Bank",
    "Country State Bank",
    "Countryside Bank",
    "County Bank",
    "Court Street Group Bank",
    "Coven Bank",
    "Covenant Bank",
    "Cowboy State Bank",
    "Crawford County Trust and Savings Bank",
    "Crescent Bank and Trust",
    "Cross Keys Bank",
    "Crossroads Bank",
    "Crystal Lake Bank and Trust",
    "Cumberland Bank",
    "Cumberland County Bank",
    "Cumberland Valley National Bank",
    "Customers Bank",
    "Dakota Community Bank and Trust",
    "Dakota Western Bank",
    "Danville State Savings Bank",
    "Davis County Bank",
    "De Novo Bank",
    "Decatur County Bank",
    "Delaware County Bank and Trust",
    "Delta Bank",
    "Delta National Bank and Trust",
    "Denmark State Bank",
    "Deposit Bank",
    "Deutsche Bank Trust Company Americas",
    "Diamond Bank",
    "Dickinson County Bank",
    "Dime Bank",
    "Dixon Bank",
    "DNB First",
    "Dolores State Bank",
    "Donnell Bank",
    "Douglas County Bank",
    "Drovers First American Bank",
    "Du Quoin State Bank",
    "DuPage Credit Union",
    "Eagle Bank",
    "Eagle Bank and Trust",
    "Eagle Savings Bank",
    "EagleBank",
    "East Cambridge Savings Bank",
    "East Penn Bank",
    "East West Bank",
    "Eastern International Bank",
    "Eastern Michigan Bank",
    "Eastern National Bank",
    "Easthampton Savings Bank",
    "Eastman Credit Union",
    "Elberton Federal Savings and Loan",
    "Electronic Federal Credit Union",
    "Elmira Savings Bank",
    "Embassy Bank for the Lehigh Valley",
    "Empire Bank",
    "Emprise Bank",
    "Encompass Bank",
    "Endeavor Bank",
    "Enterprise Bank",
    "Equitable Bank",
    "ESB Bank",
    "Essex Bank",
    "Evans Bank",
    "Everett Co-operative Bank",
    "Evergreen Federal Savings",
    "Exchange Bank of Northeast Missouri",
    "Exchange National Bank and Trust",
    "Executive National Bank",
    "Extraco Banks",
    "F&M Bank and Trust Company",
    "Fairfield County Bank",
    "Fairview State Banking Company",
    "Fall River Five Cents Savings Bank",
    "Family Bank",
    "Family Security Credit Union",
    "Far East National Bank",
    "Farm Bureau Bank",
    "Farmers and Merchants Bank",
    "Farmers and Merchants State Bank",
    "Farmers Bank and Capital Trust Company",
    "Farmers Bank and Trust",
    "Farmers Deposit Bank",
    "Farmers National Bank",
    "Farmers Savings Bank",
    "Farmers State Bank",
    "Fauquier Bank",
    "Fayette County National Bank",
    "FCNB Bank",
    "Federal Agricultural Mortgage Corporation",
    "Fidelity Co-operative Bank",
    "Fidelity Federal Savings and Loan",
    "Fifth District Savings Bank",
    "Finance Factors",
    "Financial Federal Bank",
    "Financial Partners Credit Union",
    "First American Bank and Trust",
    "First Bank Financial Centre",
    "First Bank of Highland Park",
    "First Bank of Ohio",
    "First Citizens Community Bank",
    "First Commercial Bank",
    "First Community Bank and Trust",
    "First County Bank",
    "First Credit Union",
    "First Federal Bank of the Midwest",
    "First Federal Community Bank",
    "First Federal Savings and Loan Association",
    "First Financial Bank",
    "First Financial Northwest",
    "First Green Bank",
    "First guaranty Bank",
    "First Liberty Bank",
    "First Midwest Bank",
    "First National Bank and Trust",
    "First National Bank in Howell",
    "First National Bank in Trinidad",
    "First National Bank of America",
    "First National Bank of Anderson",
    "First National Bank of Barry",
    "First National Bank of Beardstown",
    "First National Bank of Brookfield",
    "First National Bank of Coleraine",
    "First National Bank of Dighton",
    "First National Bank of Gillette",
    "First National Bank of Griffin",
    "First National Bank of Hugo",
    "First National Bank of Kansas",
    "First National Bank of Livingston",
    "First National Bank of Lacon",
    "First National Bank of Long Island",
    "First National Bank of McConnelsville",
    "First National Bank of Michigan",
    "First National Bank of Middle Tennessee",
    "First National Bank of Mount Dora",
    "First National Bank of Nebraska",
    "First National Bank of Nevada",
    "First National Bank of Nokomis",
    "First National Bank of Olathe",
    "First National Bank of Ottawa",
    "First National Bank of Pikeville",
    "First National Bank of Raymond",
    "First National Bank of Scotia",
    "First National Bank of Staunton",
    "First National Bank of Suffield",
    "First National Bank of Syracuse",
    "First National Bank of Texas",
    "First National Bank of Vandalia",
    "First National Bank of Waterloo",
    "First National Bank Texas",
    "First National Bank USA",
    "First Nebraska Bank",
    "First Peoples Bank",
    "First Priority Bank",
    "First Promise Bank",
    "First Regional Bank",
    "First Robinson Savings Bank",
    "First Savings Bank",
    "First Savings Bank Northwest",
    "First Security Bank and Trust",
    "First South Bank",
    "First State Bank Central Texas",
    "First State Bank of Arcadia",
    "First State Bank of Ben Wheeler",
    "First State Bank of Middlebury",
    "First State Bank of Newcastle",
    "First State Bank of Purdy",
    "First State Bank of Roscoe",
    "First State Bank of Uvalde",
    "First State Bank of Wyoming",
    "First Texas Bank",
    "First Trust and Savings Bank",
    "First United Bank",
    "First United Security Bank",
    "First Valley Bank",
    "First Victoria National Bank",
    "First Volunteer Bank",
    "First Western Bank and Trust",
    "FirstBank Southwest",
    "FirsTier Bank",
    "Five Star Bank",
    "Flagship Bank",
    "Flushing Bank",
    "FNB Bank",
    "FNB Community Bank",
    "Focus Bank",
    "Foothill Independent Bank",
    "Forest City Bank",
    "Fort Hood National Bank",
    "Fort Lee Federal Credit Union",
    "Fortress Bank",
    "Foundation Bank",
    "Four Oaks Bank and Trust",
    "Fox River State Bank",
    "Franklin Bank",
    "Franklin County Bank",
    "Franklin Savings Bank",
    "Franklin Synergy Bank",
    "Freedom Bank",
    "Fremont Bank",
    "Frontier Bank",
    "Frontier Community Bank",
    "FSB Bank",
    "Fulda Area Credit Union",
    "Full Spectrum Bank",
    "Furst-McNess Bank",
    "Fusion Bank",
    "G&F Financial Bank",
    "Galaxy Bank",
    "Garfield County Bank",
    "Gateway Bank of Pennsylvania",
    "Gateway Commercial Bank",
    "GCF Bank",
    "GECU",
    "German American Bank",
    "Gibsland Bank and Trust",
    "Gibson County Bank",
    "GN Bank",
    "Go Bank",
    "Gold Coast Bank",
    "Golden Belt Bank",
    "Golden Bank",
    "Golden Pacific Bank",
    "Golden State Bank",
    "Goodfield State Bank",
    "Government Employees Credit Union",
    "Grabill Bank",
    "Grand Bank",
    "Grand Ridge National Bank",
    "Grand Savings Bank",
    "Grande Communications",
    "Grandpoint Bank",
    "Grandview Bank",
    "Grant County Bank",
    "Great Midwest Bank",
    "Great Plains Bank",
    "Great River Bank",
    "GreatBanc Trust Company",
    "Greater Nevada Credit Union",
    "Green Country Bank",
    "Greenfield Banking Company",
    "Greenwood Trust Company",
    "Grew and Company Bank",
    "Grundy Bank",
    "GSL Trust",
    "Guardian Bank",
    "Guardian Savings Bank",
    "Gulf Coast Bank and Trust",
    "Gulf Capital Bank",
    "H&R Block Bank",
    "Habib American Bank",
    "Hamilton Bank",
    "Hampton Roads Bankshares",
    "Hanmi Bank",
    "Happy State Bank",
    "Harbor Bank",
    "Harvest Bank",
    "Haverhill Bank",
    "Hawaii National Bank",
    "Heartland Bank and Trust",
    "Heritage Bank of Nevada",
    "Heritage Bank of the South",
    "Heritage Community Bank",
    "Heritage Oaks Bank",
    "Heritage Southeast Bank",
    "Herring Bank",
    "HF Bar Ranch",
    "Highland Bank",
    "Hills Bank and Trust",
    "Hinsdale Bank and Trust",
    "HNB Bank",
    "Holcomb Bank",
    "Home Bank SB",
    "Home Federal Bank",
    "Home Federal Savings and Loan",
    "Home Savings Bank",
    "Home State Bank",
    "Homeland Federal Savings Bank",
    "HomeStreet Bank",
    "HomeTown Bank",
    "Hoosac Bank",
    "Horizon Bank SSB",
    "Horizon Community Bank",
    "Houston Bank and Trust",
    "Howard Bank",
    "HSBC Bank Nevada",
    "Hudson City Savings Bank",
    "Hudson Valley Bank",
    "Huntingdon Valley Bank",
    "Huron Community Bank",
    "Hyperion Bank"
]

def test_bank_name_extraction():
    """Test bank name extraction with all 500 real bank names"""
    print(f"Testing bank name extraction with {len(REAL_BANK_NAMES)} real bank names...")
    print("=" * 80)
    
    # Test with clean bank names
    print("\n1. CLEAN BANK NAMES (should return exact match):")
    print("-" * 50)
    
    clean_results = []
    for i, bank_name in enumerate(REAL_BANK_NAMES[:50], 1):  # Test first 50 clean names
        result = extract_complete_bank_name_from_line(bank_name)
        clean_results.append((bank_name, result))
        match = "✅" if result == bank_name else "❌"
        print(f"{i:2d}. {bank_name:<40} -> {result} {match}")
    
    # Test with contaminated bank names (real-world scenarios)
    print("\n\n2. CONTAMINATED BANK NAMES (with extra text):")
    print("-" * 50)
    
    contaminated_tests = [
        "VERABANK bai test Report Type:",
        "Bank of America Statement Date: 01/01/2024",
        "Wells Fargo Bank Account Number: 1234567890",
        "Chase Bank Page 1 of 5",
        "Capital One Bank Balance: $1,234.56",
        "TD Bank Report Generated on 12/31/2023",
        "PNC Bank Customer Statement",
        "Fifth Third Bank Account Summary",
        "Citizens Bank Transaction History",
        "KeyBank Monthly Statement",
        "Regions Bank Statement Period: Jan 1 - Jan 31",
        "U.S. Bank Online Banking",
        "Truist Bank Federal ID: 123456789",
        "Huntington National Bank Member FDIC",
        "First National Bank of America SWIFT: FNBAUS33",
        "Bank of New York Mellon Trust Company N.A.",
        "Northern Trust Company Private Banking",
        "State Street Bank and Trust Company Boston",
        "Goldman Sachs Bank USA Salt Lake City",
        "Morgan Stanley Bank N.A. Purchase NY",
        "Stock Yards Bank and Trust Company Louisville KY",
        "First Citizens Bank and Trust Company Raleigh NC",
        "Community Bank and Trust Company Cornelia GA",
        "Security Bank and Trust Company Owensboro KY",
        "First State Bank and Trust Company Fremont NE",
        "Farmers and Merchants Bank of Central California",
        "First National Bank and Trust Company of Oklahoma City",
        "Citizens National Bank and Trust Company of McAlester",
        "Security National Bank and Trust Company of Norman",
        "First United Bank and Trust Company Crockett TX"
    ]
    
    contaminated_results = []
    for i, test_case in enumerate(contaminated_tests, 1):
        result = extract_complete_bank_name_from_line(test_case)
        contaminated_results.append((test_case, result))
        print(f"{i:2d}. {test_case}")
        print(f"    -> {result}")
        print()
    
    # Test edge cases
    print("\n3. EDGE CASES:")
    print("-" * 50)
    
    edge_cases = [
        "",  # Empty string
        "Bank",  # Single word
        "of",  # Connecting word only
        "Bank of",  # Incomplete
        "123456789",  # Numbers only
        "BANK BANK BANK",  # Repeated words
        "The Bank",  # Starting with "The"
        "A Bank for You",  # With connecting words
        "1st National Bank",  # Starting with number
        "ABC123 Bank",  # Alphanumeric
        "Bank & Trust",  # With ampersand
        "First-Citizens Bank",  # With hyphen
        "Bank (Main Branch)",  # With parentheses
        "Bank, N.A.",  # With comma and abbreviation
        "BANK OF AMERICA, N.A."  # All caps with suffix
    ]
    
    edge_results = []
    for i, test_case in enumerate(edge_cases, 1):
        result = extract_complete_bank_name_from_line(test_case)
        edge_results.append((test_case, result))
        print(f"{i:2d}. '{test_case}' -> '{result}'")
    
    # Summary statistics
    print("\n\n4. SUMMARY STATISTICS:")
    print("=" * 50)
    
    # Clean names statistics
    clean_exact_matches = sum(1 for name, result in clean_results if result == name)
    clean_success_rate = (clean_exact_matches / len(clean_results)) * 100
    
    print(f"Clean Names Tested: {len(clean_results)}")
    print(f"Exact Matches: {clean_exact_matches}")
    print(f"Success Rate: {clean_success_rate:.1f}%")
    
    # Contaminated names statistics
    contaminated_extracted = sum(1 for test, result in contaminated_results if result is not None)
    contaminated_success_rate = (contaminated_extracted / len(contaminated_results)) * 100
    
    print(f"\nContaminated Names Tested: {len(contaminated_results)}")
    print(f"Successfully Extracted: {contaminated_extracted}")
    print(f"Extraction Rate: {contaminated_success_rate:.1f}%")
    
    # Edge cases statistics
    edge_handled = sum(1 for test, result in edge_results if result is not None and len(result) > 0)
    
    print(f"\nEdge Cases Tested: {len(edge_results)}")
    print(f"Handled Successfully: {edge_handled}")
    print(f"Handling Rate: {(edge_handled / len(edge_results)) * 100:.1f}%")
    
    # Failed cases analysis
    print("\n\n5. FAILED CASES ANALYSIS:")
    print("-" * 50)
    
    print("\nClean names that failed exact match:")
    for name, result in clean_results:
        if result != name:
            print(f"  Expected: '{name}'")
            print(f"  Got:      '{result}'")
            print()
    
    print("\nContaminated names that failed extraction:")
    for test, result in contaminated_results:
        if result is None or len(result) == 0:
            print(f"  Failed: '{test}'")
    
    print("\nEdge cases that weren't handled:")
    for test, result in edge_results:
        if result is None or len(result) == 0:
            print(f"  Failed: '{test}'")
    
    return {
        'clean_results': clean_results,
        'contaminated_results': contaminated_results,
        'edge_results': edge_results,
        'clean_success_rate': clean_success_rate,
        'contaminated_success_rate': contaminated_success_rate,
        'statistics': {
            'total_banks_tested': len(REAL_BANK_NAMES),
            'clean_tested': len(clean_results),
            'contaminated_tested': len(contaminated_results),
            'edge_tested': len(edge_results)
        }
    }

if __name__ == "__main__":
    results = test_bank_name_extraction()
    print(f"\n\nTesting completed!")
    print(f"Total real bank names available: {len(REAL_BANK_NAMES)}")
    print(f"Comprehensive test results generated.")
